{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  {{- if .Values.httpRoute.appendNamespace }}
  name: {{ template "common.names.fullname" $ }}-{{ template "common.names.namespace" $ }}
  {{- else }}
  name: {{ template "common.names.fullname" $ }}
  {{- end }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  {{- include "ms-generic.labels.AppVersion" $ | nindent 4 }}
  {{- include "ms-generic.labels.kiali" $ | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.httpRoute.rules }}
    - matches:
        {{- range .matches }}
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value | default "/" }}
        {{- end }}
      backendRefs:
        - name: {{ template "ms-generic.names.service.name" $ }}
          port: {{ include "ms-generic.names.service.port" $ }}
    {{- end }}
{{- end }}