apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "pax-prometheus.fullname" .) "pax-cert-manager" | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "pax-prometheus.namespace" . }}
  labels:
    app: {{ template "pax-prometheus.name" . }}
{{- if .Values.defaultRules }}
{{- if .Values.defaultRules.labels }}
{{ toYaml .Values.defaultRules.labels | indent 4 }}
{{- end }}
{{- if .Values.defaultRules.annotations }}
  annotations:
{{ toYaml .Values.defaultRules.annotations | indent 4 }}
{{- end }}
{{- end }}
spec:
  groups:
  - name: pax.cert-manager.rules
    rules:
      {{- if .Values.paxRules.certManager.certificateExpiringSoon.enabled }}
      - alert: CertificateExpiringSoon
        expr: "(certmanager_certificate_expiration_timestamp_seconds - time()) < 86400 * {{ .Values.paxRules.certManager.certificateExpiringSoon.days }}"
        for: {{ .Values.paxRules.certManager.certificateExpiringSoon.for }}
        labels:
          severity: warning
        annotations:
          summary: "Certificado expira em menos de {{ .Values.paxRules.certManager.certificateExpiringSoon.days }} dias"
          description: "O certificado {{`{{`}} $labels.name {{`}}`}} no namespace {{`{{`}} $labels.exported_namespace {{`}}`}} expira em {{`{{`}} $value | humanizeDuration {{`}}`}}."
      {{- end }}